"use client";

/* eslint-disable @next/next/no-img-element -- Creative previews render arbitrary external assets and intentionally bypass Next image optimization. */

import { FileCode, ImageIcon, Info, Play } from "lucide-react";
import type { Creative, HtmlPreview, NativePreview, VideoPreview } from "@/types/api";
import { useTranslation } from "@/contexts/i18n-context";
import { cn } from "@/lib/utils";

type CreativeThumbCreative = {
  format?: Creative["format"] | null;
  video?: VideoPreview | null;
  native?: NativePreview | null;
  html?: HtmlPreview | null;
  display_url?: string | null;
  final_url?: string | null;
  data_source?: Creative["data_source"];
};

export function CreativeThumb({
  creative,
  size = "md",
  showSourceBadge = true,
}: {
  creative: CreativeThumbCreative;
  size?: "sm" | "md";
  showSourceBadge?: boolean;
}) {
  const { t } = useTranslation();
  const heightClass = size === "sm" ? "h-16" : "h-20";
  const iconClass = size === "sm" ? "h-6 w-6" : "h-8 w-8";
  const playWrapClass = size === "sm" ? "h-8 w-8" : "h-10 w-10";
  const playIconClass = size === "sm" ? "h-4 w-4" : "h-5 w-5";
  const source = creative.data_source?.source || "cache";
  const sourceLabel = source === "live" ? t.previewModal.liveBadge : t.previewModal.cachedBadge;
  const sourceClass = source === "live"
    ? "bg-green-100 text-green-700 border-green-200"
    : "bg-amber-100 text-amber-700 border-amber-200";
  const badge = showSourceBadge ? (
    <span className={cn("absolute top-1 right-1 text-[10px] px-1.5 py-0.5 rounded border", sourceClass)}>
      {sourceLabel}
    </span>
  ) : null;

  if (creative.format === "VIDEO") {
    const thumbnailUrl = creative.video?.thumbnail_url;

    return (
      <div className={cn("relative bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center overflow-hidden group/thumb", heightClass)}>
        {thumbnailUrl ? (
          <>
            <img
              src={thumbnailUrl}
              alt={t.creatives.videoThumbnailAlt}
              className="w-full h-full object-cover"
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = "none";
              }}
            />
            <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
              <div className={cn("rounded-full bg-black/50 flex items-center justify-center", playWrapClass)}>
                <Play className={cn("text-white ml-0.5", playIconClass)} fill="currentColor" />
              </div>
            </div>
            {size === "md" && (
              <div className="absolute top-1 left-1 opacity-0 group-hover/thumb:opacity-100 transition-opacity">
                <div className="relative group/info">
                  <div className="flex items-center gap-1 px-1.5 py-0.5 bg-black/70 rounded text-[10px] text-gray-300">
                    <Info className="h-3 w-3" />
                    {t.creatives.previewBadge}
                  </div>
                  <div className="hidden group-hover/info:block absolute top-6 left-0 w-48 p-2 bg-gray-900 border border-gray-700 rounded-lg text-xs text-gray-300 shadow-lg z-20">
                    <p className="font-medium mb-1">{t.creatives.autoGeneratedPreview}</p>
                    <p className="text-gray-400">{t.creatives.autoGeneratedPreviewDesc}</p>
                  </div>
                </div>
              </div>
            )}
          </>
        ) : (
          <div className={cn("rounded-full bg-white/20 flex items-center justify-center", playWrapClass)}>
            <Play className={cn("text-white ml-0.5", playIconClass)} fill="currentColor" />
          </div>
        )}
        {creative.video?.duration && (
          <span className="absolute bottom-1 right-1 bg-black/70 text-white text-[10px] px-1 py-0.5 rounded">
            {creative.video.duration}
          </span>
        )}
        {badge}
      </div>
    );
  }

  if (creative.format === "NATIVE") {
    const imageUrl = creative.native?.logo?.url || creative.native?.image?.url;
    return (
      <div className={cn("relative bg-gradient-to-br from-green-50 to-green-100 flex items-center justify-center overflow-hidden", heightClass)}>
        {imageUrl ? (
          <img
            src={imageUrl}
            alt={creative.native?.headline || t.previewModal.nativeAdAlt}
            className="w-full h-full object-cover"
            onError={(e) => {
              (e.target as HTMLImageElement).style.display = "none";
            }}
          />
        ) : (
          <ImageIcon className={cn("text-green-400", iconClass)} />
        )}
        {badge}
      </div>
    );
  }

  if (creative.format === "HTML") {
    const thumbnailUrl = creative.html?.thumbnail_url;
    return (
      <div className={cn("relative bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center", heightClass)}>
        {thumbnailUrl ? (
          <img
            src={thumbnailUrl}
            alt={t.creatives.htmlPreviewAlt}
            className="w-full h-full object-cover"
            onError={(e) => {
              (e.target as HTMLImageElement).style.display = "none";
            }}
          />
        ) : (
          <FileCode className={cn("text-blue-400", iconClass)} />
        )}
        {badge}
      </div>
    );
  }

  if (creative.format === "IMAGE") {
    const candidateUrl = creative.display_url || creative.final_url || "";
    const isImageUrl = /\.(png|jpe?g|gif|webp)(\?.*)?$/i.test(candidateUrl);
    return (
      <div className={cn("relative bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center", heightClass)}>
        {isImageUrl ? (
          <img
            src={candidateUrl}
            alt={t.creatives.displayPreviewAlt}
            className="w-full h-full object-cover"
            onError={(e) => {
              (e.target as HTMLImageElement).style.display = "none";
            }}
          />
        ) : (
          <ImageIcon className={cn("text-blue-400", iconClass)} />
        )}
        {badge}
      </div>
    );
  }

  return (
    <div className={cn("relative bg-gray-100 flex items-center justify-center text-gray-400", heightClass)}>
      <ImageIcon className={iconClass} />
      {badge}
    </div>
  );
}
