const LANGUAGE_TO_COUNTRIES: Record<string, string[]> = {
  en: ["US", "GB", "CA", "AU", "NZ", "IE", "ZA", "SG", "IN", "PH", "NG", "KE", "GH"],
  de: ["DE", "AT", "CH", "LI", "LU", "BE"],
  fr: ["FR", "BE", "CH", "CA", "LU", "MC", "SN", "CI", "ML", "BF", "NE", "TG", "BJ", "MG"],
  es: ["ES", "MX", "AR", "CO", "PE", "VE", "CL", "EC", "GT", "CU", "DO", "BO", "HN", "PY", "SV", "NI", "CR", "PA", "UY", "PR"],
  it: ["IT", "CH", "SM", "VA"],
  pt: ["PT", "BR", "AO", "MZ", "CV", "GW", "ST", "TL", "MO"],
  nl: ["NL", "BE", "SR", "CW", "AW", "SX"],
  pl: ["PL"],
  ru: ["RU", "BY", "KZ", "KG"],
  ja: ["JP"],
  ko: ["KR", "KP"],
  zh: ["CN", "TW", "HK", "MO", "SG"],
  ar: ["SA", "EG", "AE", "IQ", "JO", "KW", "LB", "LY", "MA", "OM", "QA", "SD", "SY", "TN", "YE", "DZ", "BH"],
  hi: ["IN"],
  tr: ["TR", "CY"],
  th: ["TH"],
  vi: ["VN"],
  id: ["ID"],
  ms: ["MY", "SG", "BN"],
  sv: ["SE", "FI"],
  da: ["DK", "GL", "FO"],
  no: ["NO"],
  fi: ["FI"],
  cs: ["CZ"],
  el: ["GR", "CY"],
  he: ["IL"],
  hu: ["HU"],
  ro: ["RO", "MD"],
  uk: ["UA"],
  bg: ["BG"],
  hr: ["HR", "BA"],
  sr: ["RS", "BA", "ME"],
  sk: ["SK"],
  sl: ["SI"],
  et: ["EE"],
  lv: ["LV"],
  lt: ["LT"],
  bn: ["BD", "IN"],
  ta: ["IN", "LK", "SG", "MY"],
  te: ["IN"],
  mr: ["IN"],
  ur: ["PK", "IN"],
  sw: ["KE", "TZ", "UG"],
};

const LANGUAGE_NAMES: Record<string, string> = {
  ar: "Arabic",
  bg: "Bulgarian",
  bn: "Bengali",
  cs: "Czech",
  da: "Danish",
  de: "German",
  el: "Greek",
  en: "English",
  es: "Spanish",
  et: "Estonian",
  fi: "Finnish",
  fr: "French",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  id: "Indonesian",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  lt: "Lithuanian",
  lv: "Latvian",
  mr: "Marathi",
  ms: "Malay",
  my: "Myanmar",
  nl: "Dutch",
  no: "Norwegian",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  sk: "Slovak",
  sl: "Slovenian",
  sr: "Serbian",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
  zh: "Chinese",
};

const LANGUAGE_NAMES_ZH: Record<string, string> = {
  ar: "阿拉伯语",
  bg: "保加利亚语",
  bn: "孟加拉语",
  cs: "捷克语",
  da: "丹麦语",
  de: "德语",
  el: "希腊语",
  en: "英语",
  es: "西班牙语",
  et: "爱沙尼亚语",
  fi: "芬兰语",
  fr: "法语",
  he: "希伯来语",
  hi: "印地语",
  hr: "克罗地亚语",
  hu: "匈牙利语",
  id: "印尼语",
  it: "意大利语",
  ja: "日语",
  ko: "韩语",
  lt: "立陶宛语",
  lv: "拉脱维亚语",
  mr: "马拉地语",
  ms: "马来语",
  my: "缅甸语",
  nl: "荷兰语",
  no: "挪威语",
  pl: "波兰语",
  pt: "葡萄牙语",
  ro: "罗马尼亚语",
  ru: "俄语",
  sk: "斯洛伐克语",
  sl: "斯洛文尼亚语",
  sr: "塞尔维亚语",
  sv: "瑞典语",
  sw: "斯瓦希里语",
  ta: "泰米尔语",
  te: "泰卢固语",
  th: "泰语",
  tr: "土耳其语",
  uk: "乌克兰语",
  ur: "乌尔都语",
  vi: "越南语",
  zh: "中文",
};

const COUNTRY_NAMES: Record<string, string> = {
  AE: "United Arab Emirates",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BE: "Belgium",
  BR: "Brazil",
  CA: "Canada",
  CH: "Switzerland",
  CN: "China",
  CO: "Colombia",
  DE: "Germany",
  DK: "Denmark",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  HK: "Hong Kong",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IT: "Italy",
  JP: "Japan",
  KR: "South Korea",
  MX: "Mexico",
  MY: "Malaysia",
  NL: "Netherlands",
  NZ: "New Zealand",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  RU: "Russia",
  SA: "Saudi Arabia",
  SE: "Sweden",
  SG: "Singapore",
  TH: "Thailand",
  TR: "Turkey",
  TW: "Taiwan",
  UA: "Ukraine",
  US: "United States",
  VN: "Vietnam",
  ZA: "South Africa",
};

const COUNTRY_NAMES_ZH: Record<string, string> = {
  AE: "阿联酋",
  ARE: "阿联酋",
  AR: "阿根廷",
  ARG: "阿根廷",
  AT: "奥地利",
  AUT: "奥地利",
  AU: "澳大利亚",
  AUS: "澳大利亚",
  BE: "比利时",
  BEL: "比利时",
  BR: "巴西",
  BRA: "巴西",
  CA: "加拿大",
  CAN: "加拿大",
  CH: "瑞士",
  CHE: "瑞士",
  CL: "智利",
  CHL: "智利",
  CN: "中国",
  CHN: "中国",
  CO: "哥伦比亚",
  COL: "哥伦比亚",
  DE: "德国",
  DEU: "德国",
  DK: "丹麦",
  DNK: "丹麦",
  ES: "西班牙",
  ESP: "西班牙",
  FI: "芬兰",
  FIN: "芬兰",
  FR: "法国",
  FRA: "法国",
  GB: "英国",
  GBR: "英国",
  HK: "香港",
  HKG: "香港",
  ID: "印度尼西亚",
  IDN: "印度尼西亚",
  IE: "爱尔兰",
  IRL: "爱尔兰",
  IL: "以色列",
  ISR: "以色列",
  IN: "印度",
  IND: "印度",
  IT: "意大利",
  ITA: "意大利",
  JP: "日本",
  JPN: "日本",
  KR: "韩国",
  KOR: "韩国",
  MX: "墨西哥",
  MEX: "墨西哥",
  MY: "马来西亚",
  MYS: "马来西亚",
  NL: "荷兰",
  NLD: "荷兰",
  NZ: "新西兰",
  NZL: "新西兰",
  PH: "菲律宾",
  PHL: "菲律宾",
  PL: "波兰",
  POL: "波兰",
  PT: "葡萄牙",
  PRT: "葡萄牙",
  RU: "俄罗斯",
  RUS: "俄罗斯",
  SA: "沙特阿拉伯",
  SAU: "沙特阿拉伯",
  SE: "瑞典",
  SWE: "瑞典",
  SG: "新加坡",
  SGP: "新加坡",
  TH: "泰国",
  THA: "泰国",
  TR: "土耳其",
  TUR: "土耳其",
  TW: "台湾",
  TWN: "台湾",
  UA: "乌克兰",
  UKR: "乌克兰",
  US: "美国",
  USA: "美国",
  VN: "越南",
  VNM: "越南",
  ZA: "南非",
  ZAF: "南非",
};

export function getLanguageName(
  languageCode: string | null | undefined,
  fallback?: string | null,
  locale?: string
): string | null {
  if (!languageCode && fallback) return fallback;
  if (!languageCode) return null;
  const normalized = languageCode.toLowerCase();
  if (locale?.startsWith("zh")) {
    return LANGUAGE_NAMES_ZH[normalized] || fallback || normalized.toUpperCase();
  }
  return LANGUAGE_NAMES[normalized] || fallback || normalized.toUpperCase();
}

export function getCountryName(countryCode: string | null | undefined, locale?: string): string | null {
  if (!countryCode) return null;
  const normalized = countryCode.toUpperCase();
  if (locale?.startsWith("zh")) {
    return COUNTRY_NAMES_ZH[normalized] || normalized;
  }
  return COUNTRY_NAMES[normalized] || normalized;
}

export function countryFlag(countryCode: string | null | undefined): string {
  if (!countryCode || !/^[a-z]{2}$/i.test(countryCode)) return "";
  return countryCode
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}

export function isLanguageCountryMismatch(
  languageCode: string | null | undefined,
  countryCode: string | null | undefined
): boolean {
  if (!languageCode || !countryCode) return false;
  const normalizedLang = languageCode.toLowerCase();
  const normalizedCountry = countryCode.toUpperCase();
  const expected = LANGUAGE_TO_COUNTRIES[normalizedLang];
  if (!expected || expected.length === 0) return false;
  return !expected.includes(normalizedCountry);
}
